### PR TITLE
Add additional amp cache test domains

### PR DESCRIPTION
**Pull request by dknecht**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
LGTM once the CLA is signed.

**Comment by dknecht** [comment]
I signed it!  CLA signed under CloudFlare

**Comment by dknecht** [comment]
@sebastianbenz  I might have messed up the CLA bot when I closed and reopened by accident.

**Comment by sebastianbenz** [comment]
It should work if your commit's email address is one of the email addresses associated with your companies CLA.

**Comment by sebastianbenz** [comment]
Now live at https://rocky-sierra-1919.herokuapp.com.

**Pull request merged**
