### PR TITLE
Make `amp-document` its own npm module

### LINKED ISSUE #54: Publish react-amp-document
Would be great to publish `react-amp-document` (or similarly named) on NPM, so others can easily use it.

Just giving this component its own package.json should be good enough.
https://github.com/ampproject/amp-publisher-sample/blob/master/amp-pwa/src/components/amp-document.js

### PR DESCRIPTION
**Pull request by choumx**
Fixes #54.

### CODE REVIEW

**Comment by cramforce** [comment]
Could you make a short dedicated README with a description and usage statemement?

**Comment by choumx** [comment]
> Could you make a short dedicated README with a description and usage statement?

Good idea, done!

**Comment by choumx** [comment]
More work is needed here. NPM doesn't support ES6 so I'll need to add a small build step with transpilation, and a new `react-amp-document.js` file that exports the transpiled distribution files.

**Pull request merged**
