### PR TITLE
Move existing src to subdir amp-paywall-demo/

### PR DESCRIPTION
**Pull request by choumx**
In preparation for AMP PWA to live in this repository.

### CODE REVIEW

**Comment by choumx** [comment]
@cramforce @dvoytenko

**Comment by cramforce** [comment]
Could you make a new global README.md that just links to a list of demos?

**Comment by sebastianbenz** [comment]
Why the rename? The folder contains samples for:

* amp-access
* amp-analytics
* amp-user-notification

**Comment by cramforce** [comment]
We'd like to introduce a new PWA example. Suggestion for a better name?

**Comment by sebastianbenz** [comment]
How about:

* amp-paywall-demo
* amp-pwa-demo

**Comment by choumx** [comment]
How about `extended-components-demo`?

**Comment by cramforce** [comment]
`amp-paywall-demo` sounds good to me.

**Comment by cramforce** [comment]
One more change. Keep LICENSE file in top level dir.

**Comment by cramforce** [comment]
LGTM

**Pull request merged**
